version: '3.8'

networks:
  sms_network:
    name: sms_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24


services:
  telegram_bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    environment:
      - OPEN_WEATHER_TOKEN=${OPEN_WEATHER_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GOOGLE_API_TOKEN=${GOOGLE_API_TOKEN}
      - MQTT_CLIENT_CERT=/app/certs/client.crt
      - MQTT_CLIENT_KEY=/app/certs/client.key
      - MQTT_CA_CERT=/app/certs/ca.crt
    volumes:
      - ./telegram-bot/certs:/app/certs
    restart: unless-stopped

  telegram_sms_bot:
    build:
      context: ./telegram-sms-bot
    container_name: telegram-sms-bot
    environment:
      - TELEGRAM_SMS_BOT_TOKEN=${TELEGRAM_SMS_BOT_TOKEN}
    ports:
      - "5500:5500"
    networks:
      sms_network:
        ipv4_address: 172.30.0.20  # Fixed IP for smsbox

    restart: unless-stopped

  kannel:
    build:
      context: kannel
    container_name: kannel-bearerbox
    entrypoint:
      - /usr/sbin/bearerbox
      - /etc/kannel/kannel.conf

    networks:
      sms_network:
        ipv4_address: 172.30.0.11  # Fixed IP for bearerbox
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf  # Mount local kannel.conf
    restart: unless-stopped

  smsbox:
    build:
      context: kannel
    container_name: kannel-smsbox
    entrypoint:
      - /usr/sbin/smsbox
      - /etc/kannel/kannel.conf
    networks:
      sms_network:
        ipv4_address: 172.30.0.10  # Fixed IP for smsbox
    ports:
      - "13013:13013"
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf  # Mount local kannel.conf
    restart: unless-stopped
